### ISSUE TITLE
Kb 3035583 keeps reinstalling every day

### ISSUE THREAD

**Issue by niente0** [rn10950/I-Dont-Want-Windows-10#2]
Hello, I used "I don't want Windows 10 v3.0" in Advanced mode, but every day the infamous Kb3035583 just keeps reinstalling. Any solution?

**Comment by emahiser** [comment]
Yes, got to Windows Update and find that update and right click it and HIDE.

**Comment by rn10950** [comment]
I know this can be an issue, I was thinking about releasing an update to do this automatically, but as I figured out, I will be biting off more than I can chew. I may release an update with a warning and instructions on how to hide it though.

**Comment by emahiser** [comment]
Yah, I figured it out when it reinstalled that update.  But that would be a GREAT idea though. Keep up up the GREAT work!

**Comment by rn10950** [comment]
I have pushed out v4 that adds the prompt instructing users how to hide the update.
