### ISSUE TITLE
[Feature request] Add Linux builds

### ISSUE THREAD

**Issue by agibalov** [rn10950/I-Dont-Want-Windows-10#3]
I'm on Linux, but still want to make sure I don't get Windows 10 one day. It would be very nice to have this app available on Linux.

**Comment by emahiser** [comment]
There is no reason to have this app for Linux. This is for WINDOWS.

**Comment by rn10950** [comment]
This application uninstalls KB3035583 from an already-infected Windows system, so it will have no use on a Linux system.
